### ISSUE TITLE
No data flowing from Loxone into the InfluxDB I guess

### ISSUE THREAD

**Issue by koendecock** [dusanmsk/loxone-grafana#1]
Hi,

I followed the quickstart and my docker image is starting up successfully, but what do you mean with 

- you should see some messages from loxone in loxone2influx image (Stored ..., Skipped ...)

the only messages concerning loxone2influx I see in the logging after starting run.sh are 
loxone2influx_1     | 10:11:38.611 [main] INFO  Main - Connecting ...
loxone2influx_1     | 10:11:38.958 [main] INFO  Main - Connected to influx
loxone2influx_1     | 10:11:39.050 [main] INFO  Main - Connected to mqtt
loxone2influx_1     | 10:11:39.050 [main] INFO  Main - Ready

Nothing about Stored..., Skipped, ...

1. Did I try to configure something? 
2. Would it be possible to add in your quickstart a simple example how to create a graph in Grafana based on the data of a Loxone component, for example a temperature sensor?

Gr, Koen

**Comment by dusanmsk** [comment]
Did you configured node-lox-mqtt-gateway/config.json properly? Does the user exists in loxone and is able to see everything in web visualisation?

**Comment by koendecock** [comment]
Yes, I configured it, the Loxone web interface is accessible via the URL and with the "grafana" user.

{
    "winston": [{
        "Console": {
            "level": "info",
            "colorize": true,
            "timestamp": true
        }
    }],
    "mqtt": {
        "host": "mqtt://mosquitto:1883",
        "options": {
            "clientId": "node-lox-mqtt-gateway"
        }
    },
    "miniserver": {
        "host": "192.168.1.150:50000",
        "username": "grafana",
        "password": "grafana",
        "readonly": true
    }
}

Do I have to configure something in my Loxone program to send data to influx?

**Comment by koendecock** [comment]
I modified the level to verbose and now I see more in the logs

influxdb_1          | [httpd] 172.18.0.3 - grafana [09/Nov/2018:13:29:33 +0000] "POST /write?consistency=one&db=loxone&p=%5BREDACTED%5D&precision=n&rp=autogen&u=grafana HTTP/1.1" 204 0 "-" "okhttp/3.8.1" 7e63430e-e423-11e8-80bb-000000000000 2085
loxone2influx_1     | 13:29:33.024 [MQTT Call: mqtt2influx] INFO  Main - Storing lox/algemeen/verwarming/vv_verwarmingsmenger/state {"tempActual":29.9375,"tempTarget":31.392029551115037} algemeen_verwarming_vv_verwarmingsmenger
influxdb_1          | [httpd] 172.18.0.3 - grafana [09/Nov/2018:13:29:35 +0000] "POST /write?consistency=one&db=loxone&p=%5BREDACTED%5D&precision=n&rp=autogen&u=grafana HTTP/1.1" 204 0 "-" "okhttp/3.8.1" 7f9cbfaa-e423-11e8-80bc-000000000000 1389
loxone2influx_1     | 13:29:35.078 [MQTT Call: mqtt2influx] INFO  Main - Storing lox/algemeen/verwarming/vv_verwarmingsmenger/state {"tempActual":29.875,"tempTarget":31.392029551115037} algemeen_verwarming_vv_verwarmingsmenger
loxone2influx_1     | 13:29:37.893 [MQTT Call: mqtt2influx] INFO  Main - Skipping lox/buiten/weerstation/temp_buiten/state {"value":"12.1°"} buiten_weerstation_temp_buiten
loxone2influx_1     | 13:29:37.894 [MQTT Call: mqtt2influx] INFO  Main - Skipping lox/niet_toegewezen/verwarming/vv_laatste_temp_gewenste/state {"value":"31.4"} niet_toegewezen_verwarming_vv_laatste_temp_gewenste
influxdb_1          | [httpd] 172.18.0.3 - grafana [09/Nov/2018:13:29:37 +0000] "POST /write?consistency=one&db=loxone&p=%5BREDACTED%5D&precision=n&rp=autogen&u=grafana HTTP/1.1" 204 0 "-" "okhttp/3.8.1" 814b4479-e423-11e8-80bd-000000000000 1303

I suppose the data is going into my InfluxDB now. My next question is now, how can I configure graphs in Grafana based on this InfluxDB data? I'm not very familiar with grafana so it would be great to have an example on how to configure a graph based on this Loxone data.

Many thanks in advance

**Comment by koendecock** [comment]
Hi there, I managed to get the stats visible in grafana. Thanks for your Loxone-grafana project. Great work.
